# Generated by Django 4.1 on 2023-01-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.BigIntegerField()),
                ("details", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_name", models.CharField(max_length=20)),
                ("blog_created_on", models.DateTimeField(auto_now_add=True)),
                ("super_admin", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("about", models.CharField(max_length=1000)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
                ("suspended", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.BigIntegerField()),
                ("brief", models.CharField(max_length=50)),
                ("details", models.CharField(max_length=10000)),
                ("files", models.CharField(max_length=5000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
